### ISSUE TITLE
Linking fails, requires -lGL

### ISSUE THREAD

**Issue by IceDragon200** [xxuejie/mruby-gles#4]
If this built into a system mruby, opengl needs to be linked in as well

I suggest adding:

```
spec.linker.libraries << 'GL'
```

to the mrbgem.rake (for good measure)

I've only tested this on Arch Linux however

**Comment by xxuejie** [comment]
Forgive me for my ignorance: but is this something like a convention across all platforms? I'm okay adding this flag here, but I'm concerned that this may break if some certain platforms does not use this flag.

**Comment by IceDragon200** [comment]
Linux:
-lGL

Mac: 
-framework OpenGL

Windows:
-lopengl32

I believe that's all of them.

**Comment by xxuejie** [comment]
In this case I suggest we don't add the flag here, and let the user decide what they need to add by themselves.

One more thing to notice is that this is a binding for OpenGL ES, not OpenGL. So besides the 3 platforms listed here, we have all sorts of embedded devices such as Raspberry Pi, iOS device, Android device, and so on. I don't want to take the risk of breaking builds of any platform here. After all, it's more easier to add a flag than get rid of a wrong flag in config, isn't it?

**Comment by IceDragon200** [comment]
I understand, that would be a big problem in the long run, however a nice little note in the README; stating that you must "link OpenGL into the build yourself", would be nice.

**Comment by xxuejie** [comment]
Good call! Already added a note in README. Let me know if it doesn't make sense
